apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml-agent
spec:
  destination:
    name: ''
    namespace: clearml
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/clearml-agent
    repoURL: 'https://github.com/clearml/clearml-helm-charts.git'
    targetRevision: clearml-agent-5.3.0
    sources: []
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: agentk8sglue.defaultContainerImage
          value: ubuntu:18.04
        - name: agentk8sglue.extraEnvs[0].name
          value: CLEARML_AGENT_NO_UPDATE
        - name: agentk8sglue.extraEnvs[0].value
          value: 'true'
        - name: sessions.svcType
          value: ClusterIP
        - name: agentk8sglue.apiServerUrlReference
          value: 'https://api.schneiderhh.qzz.io'
        - name: agentk8sglue.fileServerUrlReference
          value: 'https://files.schneiderhh.qzz.io'
        - name: agentk8sglue.webServerUrlReference
          value: 'https://app.schneiderhh.qzz.io'
        - name: clearml.agentk8sglueKey
          value: X62DY1AMJ382FNLKJGU6PTEYCDNEWT
        - name: clearml.agentk8sglueSecret
          value: EYi-n2JGMXxqv8UsXSjQSmV08kI9mpwuKhwfBWc2-8Pa5MVqkw2sgOht9RrvLKDQal4
  sources: []
  project: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
