apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml
  namespace: argocd
spec:
  project: default
  source:
    chart: clearml
    repoURL: https://clearml.github.io/helm-charts
    targetRevision: 7.14.7
    values: |
      apiserver:
        service:
          type: ClusterIP
      ingress:
        enabled: true
        hostName: "api.clearml.schneiderhh.qzz.io"
      fileserver:
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostName: "files.clearml.schneiderhh.qzz.io"
      webserver:
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostName: "app.clearml.schneiderhh.qzz.io"
      redis:
        architecture: replication
        master:
          persistence:
            enabled: true
            accessModes:
              - ReadWriteOnce
            size: 5Gi
            ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
            storageClass: null
        replica:
          replicaCount: 2
      mongodb:
        enabled: true
        architecture: replicaset
        replicaCount: 2
        arbiter:
          enabled: false
        pdb:
          create: true
        podAntiAffinityPreset: soft
      elasticsearch:
        replicas: 3
    helm:
      releaseName: clearml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: clearml