apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    name: ''
    namespace: loki
    server: 'https://kubernetes.default.svc'
  source:
    path: production/helm/loki
    repoURL: 'https://github.com/grafana/loki.git'
    targetRevision: HEAD
    helm:
      parameters:
        - name: loki.storage.bucketNames.chunks
          value: loki-chunks
        - name: loki.storage.bucketNames.ruler
          value: loki-ruler
        - name: loki.storage.filesystem.chunksdirectory
          value: /tmp/loki-chunks
        - name: loki.storage.filesystem.indexdirectory
          value: /tmp/loki-index
        - name: loki.commonConfig.replicationFactor
          value: '1'
        - name: loki.schemaConfig.configs[0].from
          value: '2024-04-01'
        - name: loki.schemaConfig.configs[0].store
          value: tsdb
        # - name: loki.schemaConfig.configs[0].objectStore
        #   value: filesystem
        - name: loki.schemaConfig.configs[0].schema
          value: v13
        - name: loki.schemaConfig.configs[0].index.prefix
          value: index_loki_
        - name: loki.schemaConfig.configs[0].index.period
          value: 24h
        - name: loki.storageConfig.fs.directory
          value: /tmp/loki-data
        - name: loki.pattern_ingester.enabled
          value: 'true'
        - name: loki.limits_config.allow_structured_metadata
          value: 'true'
        - name: loki.limits_config.volume_enabled
          value: 'true'
        - name: loki.ruler.enable_api
          value: 'true'
        - name: deploymentMode
          value: SingleBinary
        - name: SingleBinary.replicas
          value: '1'
        - name: backend.replicas
          value: '0'
        - name: read.replicas
          value: '0'
        - name: write.replicas
          value: '0'
        - name: ingester.replicas
          value: '0'
        - name: distributor.replicas
          value: '0'
        - name: querier.replicas
          value: '0'
        - name: ruler.replicas
          value: '0'
        - name: queryFrontend.replicas
          value: '0'
        - name: queryScheduler.replicas
          value: '0'
        - name: compactor.replicas
          value: '0'
        - name: indexGateway.replicas
          value: '0'
        - name: bloomCompactor.replicas
          value: '0'
        - name: bloomGateway.replicas
          value: '0'
  sources: []
  project: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
